### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by malhuda2** [chimemoo/ppdb#10]
Boleh minta db nya gan?

**Comment by chimemoo** [comment]
maaf gan masih dallam tahap development hehe

**Comment by malhuda2** [comment]
Oke gan :smiley: ditunggu gan , versi akhirnya

**Comment by chimemoo** [comment]
@malhuda2 siap gan

**Comment by ipzelhakim** [comment]
gimana gan?udah ada database nya?

**Comment by chimemoo** [comment]
Sudah di add ya, namun masih ada eror, silahkan pull kemudian edit lalu pull request
